#ifndef LIBDNG_EVENT_H
#define LIBDNG_EVENT_H

enum DNG_Event_Id {
	DNG_INPUT_ATTACK,
	DNG_INPUT_ENTITY,
	DNG_OUTPUT_ATTACK,
	DNG_OUTPUT_COMBAT_BEGIN,
	DNG_OUTPUT_COMBAT_END,
	DNG_OUTPUT_DAMAGE,
	DNG_OUTPUT_END,
	DNG_OUTPUT_NEXT_ROUND
};

#endif
